// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnRedQRVh9eQf0xrE-EJUc5BnVJ7vWno0',
    appId: '1:6588628291:web:b3d4cfa259b98c812d43f6',
    messagingSenderId: '6588628291',
    projectId: 'omen-1eb1c',
    authDomain: 'omen-1eb1c.firebaseapp.com',
    databaseURL: 'https://omen-1eb1c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'omen-1eb1c.firebasestorage.app',
    measurementId: 'G-B28K64PXNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFIOITxtAbcD0T3SR12y2z0QZP8l_Xn0Y',
    appId: '1:6588628291:android:cbe865098c0ea79d2d43f6',
    messagingSenderId: '6588628291',
    projectId: 'omen-1eb1c',
    databaseURL: 'https://omen-1eb1c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'omen-1eb1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnSutIaqmML-usZPXGtrtrHXwOqZxl20s',
    appId: '1:6588628291:ios:2cc982d474970d622d43f6',
    messagingSenderId: '6588628291',
    projectId: 'omen-1eb1c',
    databaseURL: 'https://omen-1eb1c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'omen-1eb1c.firebasestorage.app',
    iosClientId: '6588628291-55i6h1chk7gvb7i2k1o1askkd2asa6s6.apps.googleusercontent.com',
    iosBundleId: 'com.example.omenVaultV3',
  );
}